name: Nightly Promotion Check

on:
  schedule:
    - cron: "0 14 * * *"  # Every day at 7:00 AM Pacific (14:00 UTC)
  workflow_dispatch:       # Allows manual triggering too

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run promotion check
        run: python check_promotions.py
